resource "aws_key_pair" "dove-key" { # resource to create key pair in AWS
  # resource name is "dove-key" and type is "aws_key_pair"
  key_name = "dove-key" # name of the key pair
  # key name is "dove-key"
  public_key = "ssh-xxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" # public key of the key pair
  # public key is used to create the key pair in AWS
  # public key is used to connect to the instance
  # It is Generated by using ssh-keygen command in local machine in same directory where terraform file is created.
}
